# Generated by Django 4.2.10 on 2026-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student_limit',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
