# Generated by Django 4.2.10 on 2026-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_student_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
