# Generated by Django 4.2.10 on 2026-03-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringlog',
            name='snapshot',
        ),
    ]
